# Taskfile.yml
# Root task file for the monorepo.
# This file includes tasks from all sub-projects, allowing you to run them from the root.
version: '3'

includes:
  sdk:     { taskfile: loop/sdk/Taskfile.yml,     dir: loop/sdk }
  records: { taskfile: loop/records/Taskfile.yml, dir: loop/records }
  rewards: { taskfile: loop/rewards/Taskfile.yml, dir: loop/rewards }
  demo:    { taskfile: demo/Taskfile.yml,       dir: demo }

tasks:
  default:
    desc: 'Show available tasks. Run `task bootstrap` for first-time setup.'
    cmds:
      - task -l

  bootstrap:
    desc: "One-command setup: Install deps, generate client, and run tests."
    cmds:
      - echo "--- Bootstrapping Project ---"
      - bun install
      - task: generate:client
      - task: records:test
      - task: rewards:test

  clean:
    desc: "Remove all generated files, caches, and dependencies"
    cmds:
      - echo "--- Cleaning Project ---"
      - rm -rf node_modules
      - find . -name "node_modules" -type d -prune -exec rm -rf '{}' +
      - find . -name "dist" -type d -prune -exec rm -rf '{}' +
      - rm -rf loop/sdk/src/client
      - rm -rf loop/records/records.db*

  generate:client:
    desc: "Generate the SDK client from the records API (starts server automatically)"
    cmds:
      - task records:prod &
      - |
        echo "Waiting for records API to be ready..."
        until curl -s -f -o /dev/null http://localhost:8787/v1/openapi.json; do
          printf '.'
          sleep 1
        done
        echo "\nAPI is ready. Generating client..."
      - task: sdk:generate:client
    # The records:prod task will continue running in the background.
    # You can stop it manually with `kill <PID>` or by stopping the terminal session.
