# /Taskfile.yml
version: '3'

includes:
  contracts: { taskfile: contracts/Taskfile.yml, dir: contracts }
  sdk: { taskfile: loop/sdk/Taskfile.yml, dir: loop/sdk }
  records: { taskfile: loop/records/Taskfile.yml, dir: loop/records }
  rewards: { taskfile: loop/rewards/Taskfile.yml, dir: loop/rewards }
  demo: { taskfile: demo/Taskfile.yml, dir: demo }

tasks:
  default:
    desc: 'Show all available commands for the monorepo'
    cmds:
      - task -l

  # --- High-Level Commands ---

  build-all:
    desc: 'Build all packages in the monorepo'
    cmds:
      - bun install
      - task: contracts:build
      - task: sdk:build
      - task: records:build
      - task: rewards:build
      - task: demo:build

  test-all:
    desc: 'Run all tests in the monorepo'
    cmds:
      - task: contracts:test
      - task: records:test
      - task: rewards:test
      - task: demo:test

  format-all:
    desc: 'Format all code in the monorepo'
    cmds:
      - task: demo:format

  clean-all:
    desc: 'Clean all build artifacts and dependencies'
    cmds:
      - task: contracts:clean
      - task: sdk:clean
      - task: records:clean
      - task: rewards:clean
      - task: demo:clean
      - rm -rf node_modules