# loop/records/Taskfile.yml
version: '3'

tasks:
  default:
    desc: 'Show available tasks for the records service'
    cmds:
      - task -l

  build:
    desc: 'Build the service for production'
    cmds:
      - tsc

  dev:
    desc: 'Start the development server with hot-reloading'
    deps:
      - db:setup
    cmds:
      - bun --hot src/server.ts

  prod:
    desc: 'Start the production server'
    deps:
      - db:setup
    cmds:
      - bun src/server.ts

  test:
    desc: 'Run the unit tests'
    cmds:
      - bun test

  typecheck:
    desc: 'Type-check the project without emitting files'
    cmds:
      - tsc --noEmit

  clean:
    desc: 'Remove build artifacts and database files'
    cmds:
      - rm -rf dist *.db *.db-journal

  db:setup:
    desc: 'Initialize and seed the database'
    cmds:
      - bun run src/db/init.ts
      - bun run src/db/seed.ts

  db:seed-judges:
    desc: 'Seed the database with the judges campaign'
    cmds:
      - bun run src/db/seed-judges.ts