version: '3'

tasks:
  default:
    desc: "Show available tasks for the records service"
    cmds:
      - task -l

  setup:
    desc: "Initialize and seed the database"
    cmds:
      - task: db:init
      - task: db:seed

  prod:
    desc: "Start the production server"
    deps: [setup]
    cmds:
      - bun run {{.TASKFILE_DIR}}/src/server.ts

  dev:
    desc: "Start the development server with hot-reloading"
    deps: [setup]
    cmds:
      - bun --hot run {{.TASKFILE_DIR}}/src/server.ts

  typecheck:
    desc: "Type-check the project without emitting files"
    cmds:
      - tsc --noEmit

  db:init:
    desc: "Initialize the database from the schema file"
    cmds:
      - bun run src/db/init.ts

  db:seed:
    desc: "Seed the database with initial data"
    cmds:
      - bun run src/db/seed.ts
  
  test:
    desc: "Run the unit tests with Bun"
    cmds:
      - bun test

  clean:
    desc: "Remove build artifacts"
    cmds:
      - rm -rf dist
