version: '3'

tasks:
  default:
    desc: "Show available tasks for the records service"
    cmds:
      - task -l

  setup:
    desc: "Initialize and seed the database"
    cmds:
      - task: db:init
      - task: db:seed

  start:
    desc: "Start the production server"
    cmds:
      # Use {{.TASKFILE_DIR}} to ensure the path is always correct
      - bun {{.TASKFILE_DIR}}/dist/server.js

  stop:
    desc: "Stop the server"
    cmds:
      - pkill -f 'bun {{.TASKFILE_DIR}}/dist/server.js' || true

  build:
    desc: "Build the project for production"
    cmds:
      - tsc

  typecheck:
    desc: "Type-check the project without emitting files"
    cmds:
      - tsc --noEmit

  db:init:
    desc: "Initialize the database from the schema file"
    cmds:
      - bun run src/db/init.ts

  db:seed:
    desc: "Seed the database with initial data"
    cmds:
      - bun run src/db/seed.ts
  
  test:
    desc: "Run the unit tests with Bun"
    cmds:
      - bun test

  clean:
    desc: "Remove build artifacts"
    cmds:
      - rm -rf dist