# loop/records/Taskfile.yml
version: '3'

tasks:
  default:
    desc: 'Show available tasks for the records service'
    cmds:
      - task -l

  dev:
    desc: 'Start the development server with hot-reloading'
    cmds:
      - bun --hot src/server.ts

  start:
    desc: 'Start the production server'
    cmds:
      - bun src/server.ts

  test:
    desc: 'Run the unit tests'
    cmds:
      - bun test

  clean:
    desc: 'Remove build artifacts and database files'
    cmds:
      - rm -rf dist *.db *.db-journal

  db:setup:
    desc: 'Initialize and seed the database with default data'
    cmds:
      - bun run src/db/init.ts
      - bun run src/db/seed.ts

  db:seed-judges:
    desc: 'Initialize and seed the database with the judges campaign'
    deps:
      - db:init
    cmds:
      - bun run src/db/seed-judges.ts

  db:init:
    desc: 'Initialize the database schema'
    cmds:
      - bun run src/db/init.ts
