# loop/sdk/Taskfile.yml
version: '3'

tasks:
  default:
    desc: 'Show available tasks for the sdk package'
    cmds:
      - task -l

  generate:client:
    desc: 'Generate the API client from the records service OpenAPI spec'
    cmds:
      - bun run generate:client

  clean:
    desc: 'Remove build artifacts'
    cmds:
      - rm -rf dist src/client
