version: '3'

tasks:
  default:
    desc: "Show available tasks for the sdk package"
    cmds:
      - task -l

  typecheck:
    desc: "Type-check the SDK"
    cmds:
      - tsc --noEmit

  clean:
    desc: "Remove build artifacts"
    cmds:
      - rm -rf dist