version: '3'

tasks:
  default:
    desc: "Show available tasks for the sdk package"
    cmds:
      - task -l

  build:
    desc: "Build the SDK for production"
    cmds:
      - tsc

  clean:
    desc: "Remove build artifacts"
    cmds:
      - rm -rf dist
