# contracts/Taskfile.yml
version: '3'

tasks:
  default:
    desc: 'Show available tasks for the contracts package'
    cmds:
      - task -l

  build:
    desc: 'Compile the smart contracts'
    cmds:
      - bun run compile

  test:
    desc: 'Run smart contract tests'
    cmds:
      - bun run test

  clean:
    desc: 'Clear the Hardhat cache, artifacts, and deployment records'
    cmds:
      - bunx hardhat clean
      - rm -rf ignition/deployments

  node:
    desc: 'Start a local Hardhat network node'
    cmds:
      - bunx hardhat node