# demo/Taskfile.yml
version: '3'

vars:
  PROJECT_NAME: pfp2e-demo
  COMPOSE_CMD: docker compose -p {{.PROJECT_NAME}}

tasks:
  default:
    desc: 'Show available tasks for the demo app'
    cmds:
      - task -l

  build:
    desc: 'Build the Next.js app for production'
    dir: www
    cmds:
      - bun run build

  dev:
    desc: 'Start the development server'
    dir: www
    cmds:
      - bun run dev

  prod:
    desc: 'Build and start the production server'
    dir: www
    cmds:
      - bun run build
      - bun run start

  test:
    desc: 'Run the full test suite (unit + UI)'
    dir: www
    cmds:
      - bun test
      - bun run test:ui

  typecheck:
    desc: 'Type-check the project without emitting files'
    dir: www
    cmds:
      - tsc --noEmit

  clean:
    desc: 'Remove build artifacts'
    dir: www
    cmds:
      - rm -rf .next out

  # --- Container Commands ---
  # These are kept for reference but will be updated in the next phase.

  container:dev:
    desc: 'Start the development server (container)'
    cmds:
      - '{{.COMPOSE_CMD}} up -d --build dev'

  container:prod:
    desc: 'Build and start the production server (container)'
    cmds:
      - '{{.COMPOSE_CMD}} up -d --build prod'

  container:test:
    desc: 'Run the full test suite (container)'
    cmds:
      - '{{.COMPOSE_CMD}} --profile test up --build --abort-on-container-exit --exit-code-from test'
    finally:
      - '{{.COMPOSE_CMD}} down'

  container:stop:
    desc: 'Stop all running services (container only)'
    cmds:
      - '{{.COMPOSE_CMD}} down --remove-orphans'

  container:logs:
    desc: 'Follow container logs (container only)'
    cmds:
      - '{{.COMPOSE_CMD}} logs -f'

  container:clean:
    desc: 'Remove all project container assets'
    prompt: Are you sure you want to permanently delete all project container assets?
    cmds:
      - '{{.COMPOSE_CMD}} down --volumes --remove-orphans'
      - 'docker image prune -a -f --filter "label=project={{.PROJECT_NAME}}"'
