version: '3'

tasks:
  default:
    desc: "Show available tasks for the rewards service"
    cmds:
      - task -l

  prod:
    desc: "Run the rewards oracle script for production"
    cmds:
      - bun run src/index.ts

  dev:
    desc: "Run the rewards oracle script for development"
    cmds:
      - task: prod

  test:
    desc: "Tests for the rewards service (no-op)"
    cmds:
      - echo "No tests for rewards service."

  typecheck:
    desc: "Type-check the project without emitting files"
    cmds:
      - tsc --noEmit