# loop/rewards/Taskfile.yml
version: '3'

tasks:
  default:
    desc: 'Show available tasks for the rewards service'
    cmds:
      - task -l

  dev:
    desc: 'Run the rewards oracle script in watch mode'
    cmds:
      - bun --watch src/index.ts

  start:
    desc: 'Run the rewards oracle script for production'
    cmds:
      - bun src/index.ts

  test:
    desc: 'Tests for the rewards service (no-op)'
    cmds:
      - echo "No tests for rewards service."

  clean:
    desc: 'Remove build artifacts'
    cmds:
      - rm -rf dist